### PR TITLE
remove 'Running Command' logging statement

### PR DESCRIPTION
**Pull request by brianfoshee**
It's leaking env vars into drone logs.

### CODE REVIEW

**Comment by brianfoshee** [comment]
@jprobinson @jrynyt

**Comment by jrynyt** [comment]
Can you give an example? As you can see, it's not printing any environment variables; it's printing the command it's going to run.

**Comment by brianfoshee** [comment]
@jrynyt pinged you in slack, the appcfg command prints out env vars that are being set on an app.

**Comment by brianfoshee** [comment]
closing this out in favor of #20

**Pull request closed without merging**
